#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${DIR}"

if which py.test > /dev/null; then
  py.test mpnum --doctest-modules
  py.test tests tests_photonic_tomo
fi
if which py.test-3 > /dev/null; then
  py.test-3 mpnum --doctest-modules
  py.test-3 tests tests_photonic_tomo
fi

