#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${DIR}"

if python2 -c "import pytest" &> /dev/null; then
    python2 runtests.py
fi
if python3 -c "import pytest" &> /dev/null; then
    python3 runtests.py
fi

